//Electricity and Magnetism; 18 options
forms[2] = new Array();
	forms[2][1] = new Array();
		forms[2][1][0] = 4;
		forms[2][1][1] = "<td><input type=text id=a></input></td><td>Force</td><td>(F)</td><td id=image style='vertical-align: top;'></td>";
		forms[2][1][2] = "<td><input type=text id=b></input></td><td>Charge 1</td><td>(q<sub>1</sub>)</td>";
		forms[2][1][3] = "<td><input type=text id=c></input></td><td>Charge 2</td><td>(q<sub>2</sub>)</td>";
		forms[2][1][4] = "<td><input type=text id=d></input></td><td>Distance</td><td>(r)</td>";
	forms[2][2] = new Array();
		forms[2][2][0] = 3;
		forms[2][2][1] = "<td><input type=text id=a></input></td><td>Electric Field</td><td>(E)</td><td id=image style='vertical-align: top;'></td>";
		forms[2][2][2] = "<td><input type=text id=b></input></td><td>Force</td><td>(F)</td>";
		forms[2][2][3] = "<td><input type=text id=c></input></td><td>Charge</td><td>(q)</td>";
	forms[2][3] = new Array();
		forms[2][3][0] = 4;
		forms[2][3][1] = "<td><input type=text id=a></input></td><td>Potential Energy</td><td>(U)</td><td id=image style='vertical-align: top;'></td>";
		forms[2][3][2] = "<td><input type=text id=b></input></td><td>Charge 1</td><td>(q<sub>1</sub>)</td>";
		forms[2][3][3] = "<td><input type=text id=c></input></td><td>Charge 2</td><td>(q<sub>2</sub>)</td>";
		forms[2][3][4] = "<td><input type=text id=d></input></td><td>Distance</td><td>(r)</td>";
	forms[2][4] = new Array();
		forms[2][4][0] = 3;
		forms[2][4][1] = "<td><input type=text id=a></input></td><td>Electric Field</td><td>(E<sub>avg</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[2][4][2] = "<td><input type=text id=b></input></td><td>Electrical Potential</td><td>(V)</td>";
		forms[2][4][3] = "<td><input type=text id=c></input></td><td>Distance</td><td>(d)</td>";
	forms[2][5] = new Array();
		forms[2][5][0] = 3;
		forms[2][5][1] = "<td><input type=text id=a></input></td><td>Capacitence</td><td>(C)</td><td id=image style='vertical-align: top;'></td>";
		forms[2][5][2] = "<td><input type=text id=b></input></td><td>Charge</td><td>(Q)</td>";
		forms[2][5][3] = "<td><input type=text id=c></input></td><td>Electrical Potential</td><td>(V)</td>";
	forms[2][6] = new Array();
		forms[2][6][0] = 3;
		forms[2][6][1] = "<td><input type=text id=a></input></td><td>Capacitence</td><td>(C)</td><td id=image style='vertical-align: top;'></td>";
		forms[2][6][2] = "<td><input type=text id=b></input></td><td>Area</td><td>(A)</td>";
		forms[2][6][3] = "<td><input type=text id=c></input></td><td>Distance</td><td>(d)</td>";
	forms[2][7] = new Array();
		forms[2][7][0] = 3;
		forms[2][7][1] = "<td><input type=text id=a></input></td><td>Potential Energy</td><td>(U<sub>c</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[2][7][2] = "<td><input type=text id=b></input></td><td>Charge</td><td>(Q)</td>";
		forms[2][7][3] = "<td><input type=text id=c></input></td><td>Electrical Potential</td><td>(V)</td>";
	forms[2][8] = new Array();
		forms[2][8][0] = 3;
		forms[2][8][1] = "<td><input type=text id=a></input></td><td>Potential Energy</td><td>(U<sub>c</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[2][8][2] = "<td><input type=text id=b></input></td><td>Capacitence</td><td>(C)</td>";
		forms[2][8][3] = "<td><input type=text id=c></input></td><td>Electrical Potential</td><td>(V)</td>";
	forms[2][9] = new Array();
		forms[2][9][0] = 3;
		forms[2][9][1] = "<td><input type=text id=a></input></td><td>Current</td><td>(I<sub>avg</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[2][9][2] = "<td><input type=text id=b></input></td><td>Change in Charge</td><td>(&Delta;Q)</td>";
		forms[2][9][3] = "<td><input type=text id=c></input></td><td>Change in Time</td><td>(&Delta;t)</td>";
	forms[2][10] = new Array();
		forms[2][10][0] = 4;
		forms[2][10][1] = "<td><input type=text id=a></input></td><td>Resistance</td><td>(R)</td><td id=image style='vertical-align: top;'></td>";
		forms[2][10][2] = "<td><input type=text id=b></input></td><td>Resistivity</td><td>(p)</td>";
		forms[2][10][3] = "<td><input type=text id=c></input></td><td>Length</td><td>(l)</td>";
		forms[2][10][4] = "<td><input type=text id=d></input></td><td>Area</td><td>(A)</td>";
	forms[2][11] = new Array();
		forms[2][11][0] = 3;
		forms[2][11][1] = "<td><input type=text id=a></input></td><td>Electrical Potential</td><td>(V)</td><td id=image style='vertical-align: top;'></td>";
		forms[2][11][2] = "<td><input type=text id=b></input></td><td>Current</td><td>(I)</td>";
		forms[2][11][3] = "<td><input type=text id=c></input></td><td>Resistance</td><td>(R)</td>";
	forms[2][12] = new Array();
		forms[2][12][0] = 3;
		forms[2][12][1] = "<td><input type=text id=a></input></td><td>Power</td><td>(P)</td><td id=image style='vertical-align: top;'></td>";
		forms[2][12][2] = "<td><input type=text id=b></input></td><td>Current</td><td>(I)</td>";
		forms[2][12][3] = "<td><input type=text id=c></input></td><td>Electrical Potential</td><td>(V)</td>";
	forms[2][13] = new Array();
		forms[2][13][0] = 5;
		forms[2][13][1] = "<td><input type=text id=a></input></td><td>Force</td><td>(F<sub>B</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[2][13][2] = "<td><input type=text id=b></input></td><td>Charge</td><td>(q)</td>";
		forms[2][13][3] = "<td><input type=text id=c></input></td><td>Velocity</td><td>(v)</td>";
		forms[2][13][4] = "<td><input type=text id=d></input></td><td>Magnetic Field</td><td>(B)</td>";
		forms[2][13][5] = "<td><input type=text id=e></input></td><td>Angle</td><td>(&theta;)</td>";
	forms[2][14] = new Array();
		forms[2][14][0] = 5;
		forms[2][14][1] = "<td><input type=text id=a></input></td><td>Force</td><td>(F<sub>B</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[2][14][2] = "<td><input type=text id=b></input></td><td>Magnetic Field</td><td>(B)</td>";
		forms[2][14][3] = "<td><input type=text id=c></input></td><td>Current</td><td>(I)</td>";
		forms[2][14][4] = "<td><input type=text id=d></input></td><td>Length</td><td>(l)</td>";
		forms[2][14][5] = "<td><input type=text id=e></input></td><td>Angle</td><td>(&theta;)</td>";
	forms[2][15] = new Array();
		forms[2][15][0] = 3;
		forms[2][15][1] = "<td><input type=text id=a></input></td><td>Magnetic Field</td><td>(B)</td><td id=image style='vertical-align: top;'></td>";
		forms[2][15][2] = "<td><input type=text id=b></input></td><td>Current</td><td>(I)</td>";
		forms[2][15][3] = "<td><input type=text id=c></input></td><td>Distance</td><td>(r)</td>";
	forms[2][16] = new Array();
		forms[2][16][0] = 4;
		forms[2][16][1] = "<td><input type=text id=a></input></td><td>Magnetic Flux</td><td>(&Phi;<sub>m</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[2][16][2] = "<td><input type=text id=b></input></td><td>Magnetic Field</td><td>(B)</td>";
		forms[2][16][3] = "<td><input type=text id=c></input></td><td>Area</td><td>(A)</td>";
		forms[2][16][4] = "<td><input type=text id=d></input></td><td>Angle</td><td>(&theta;)</td>";
	forms[2][17] = new Array();
		forms[2][17][0] = 3;
		forms[2][17][1] = "<td><input type=text id=a></input></td><td>Electromagnetic Field</td><td>(&epsilon;<sub>avg</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[2][17][2] = "<td><input type=text id=b></input></td><td>Change in Magnetic Flux</td><td>(&Delta;&Phi;<sub>m</sub>)</td>";
		forms[2][17][3] = "<td><input type=text id=c></input></td><td>Change in Time</td><td>(&Delta;t)</td>";
	forms[2][18] = new Array();
		forms[2][18][0] = 4;
		forms[2][18][1] = "<td><input type=text id=a></input></td><td>Electromagnetic Field</td><td>(&epsilon;)</td><td id=image style='vertical-align: top;'></td>";
		forms[2][18][2] = "<td><input type=text id=b></input></td><td>Magnetic Field</td><td>(B)</td>";
		forms[2][18][3] = "<td><input type=text id=c></input></td><td>Length</td><td>(l)</td>";
		forms[2][18][4] = "<td><input type=text id=d></input></td><td>Velocity</td><td>(v)</td>";