//Newtonian Mechanics; 21 options
forms[1] = new Array();
	forms[1][1] = new Array();
		forms[1][1][0] = 4;
		forms[1][1][1] = "<td><input type=text id=a></input></td><td>Final Velocity</td><td>(v<sub>f</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][1][2] = "<td><input type=text id=b></input></td><td>Initial Velocity</td><td>(v<sub>i</sub>)</td>";
		forms[1][1][3] = "<td><input type=text id=c></input></td><td>Acceleration</td><td>(a)</td>";
		forms[1][1][4] = "<td><input type=text id=d></input></td><td>Time</td><td>(t)</td>";
	forms[1][2] = new Array();
		forms[1][2][0] = 5;
		forms[1][2][1] = "<td><input type=text id=a></input></td><td>Final Distance</td><td>(x<sub>f</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][2][2] = "<td><input type=text id=b></input></td><td>Initial Distance</td><td>(x<sub>i</sub>)</td>";
		forms[1][2][3] = "<td><input type=text id=c></input></td><td>Initial Velocity</td><td>(v<sub>i</sub>)</td>";
		forms[1][2][4] = "<td><input type=text id=d></input></td><td>Time</td><td>(t)</td>";
		forms[1][2][5] = "<td><input type=text id=e></input></td><td>Acceleration</td><td>(a)</td>";
	forms[1][3] = new Array();
		forms[1][3][0] = 5;
		forms[1][3][1] = "<td><input type=text id=a></input></td><td>Final Velocity</td><td>(v<sub>f</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][3][2] = "<td><input type=text id=b></input></td><td>Initial Velocity</td><td>(v<sub>i</sub>)</td>";
		forms[1][3][3] = "<td><input type=text id=c></input></td><td>Acceleration</td><td>(a)</td>";
		forms[1][3][4] = "<td><input type=text id=d></input></td><td>Final Distance</td><td>(x<sub>f</sub>)</td>";
		forms[1][3][5] = "<td><input type=text id=e></input></td><td>Initial Distance</td><td>(x<sub>i</sub>)</td>";
	forms[1][4] = new Array();
		forms[1][4][0] = 3;
		forms[1][4][1] = "<td><input type=text id=a></input></td><td>Force</td><td>(F<sub>net</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][4][2] = "<td><input type=text id=b></input></td><td>Mass</td><td>(m)</td>";
		forms[1][4][3] = "<td><input type=text id=c></input></td><td>Acceleration</td><td>(a)</td>";
	forms[1][5] = new Array();
		forms[1][5][0] = 3;
		forms[1][5][1] = "<td><input type=text id=a></input></td><td>Force</td><td>(F<sub>fric</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][5][2] = "<td><input type=text id=b></input></td><td>Coefficient of Friction</td><td>(&micro;)</td>";
		forms[1][5][3] = "<td><input type=text id=c></input></td><td>Normal Force</td><td>(N)</td>";
	forms[1][6] = new Array();
		forms[1][6][0] = 3;
		forms[1][6][1] = "<td><input type=text id=a></input></td><td>Accleration</td><td>(a<sub>c</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][6][2] = "<td><input type=text id=b></input></td><td>Velocity</td><td>(v)</td>";
		forms[1][6][3] = "<td><input type=text id=c></input></td><td>Radius</td><td>(r)</td>";
	forms[1][7] = new Array();
		forms[1][7][0] = 4;
		forms[1][7][1] = "<td><input type=text id=a></input></td><td>Torque</td><td>(&tau;)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][7][2] = "<td><input type=text id=b></input></td><td>Radius</td><td>(r)</td>";
		forms[1][7][3] = "<td><input type=text id=c></input></td><td>Force</td><td>(F)</td>";
		forms[1][7][4] = "<td><input type=text id=d></input></td><td>Angle</td><td>(&theta;)</td>";
	forms[1][8] = new Array();
		forms[1][8][0] = 3;
		forms[1][8][1] = "<td><input type=text id=a></input></td><td>Momentum</td><td>(p)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][8][2] = "<td><input type=text id=b></input></td><td>Mass</td><td>(m)</td>";
		forms[1][8][3] = "<td><input type=text id=c></input></td><td>Velocity</td><td>(v)</td>";
	forms[1][9] = new Array();
		forms[1][9][0] = 3;
		forms[1][9][1] = "<td><input type=text id=a></input></td><td>Impulse</td><td>(J)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][9][2] = "<td><input type=text id=b></input></td><td>Force</td><td>(F)</td>";
		forms[1][9][3] = "<td><input type=text id=c></input></td><td>Change in Time</td><td>(&Delta;t)</td>";
	forms[1][10] = new Array();
		forms[1][10][0] = 3;
		forms[1][10][1] = "<td><input type=text id=a></input></td><td>Kinetic Energy</td><td>(K)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][10][2] = "<td><input type=text id=b></input></td><td>Mass</td><td>(m)</td>";
		forms[1][10][3] = "<td><input type=text id=c></input></td><td>Velocity</td><td>(v)</td>";
	forms[1][11] = new Array();
		forms[1][11][0] = 4;
		forms[1][11][1] = "<td><input type=text id=a></input></td><td>Change in Potential Energy</td><td>(&Delta;U<sub>g</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][11][2] = "<td><input type=text id=b></input></td><td>Mass</td><td>(m)</td>";
		forms[1][11][3] = "<td><input type=text id=c></input></td><td>Acceleration from Gravity</td><td>(g)</td>";
		forms[1][11][4] = "<td><input type=text id=d></input></td><td>Height</td><td>(h)</td>";
	forms[1][12] = new Array();
		forms[1][12][0] = 4;
		forms[1][12][1] = "<td><input type=text id=a></input></td><td>Work</td><td>(W)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][12][2] = "<td><input type=text id=b></input></td><td>Force</td><td>(F)</td>";
		forms[1][12][3] = "<td><input type=text id=c></input></td><td>Change in Distance</td><td>(&Delta;r)</td>";
		forms[1][12][4] = "<td><input type=text id=d></input></td><td>Angle</td><td>(&theta;)</td>";
	forms[1][13] = new Array();
		forms[1][13][0] = 3;
		forms[1][13][1] = "<td><input type=text id=a></input></td><td>Power</td><td>(P<sub>avg</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][13][2] = "<td><input type=text id=b></input></td><td>Work</td><td>(W)</td>";
		forms[1][13][3] = "<td><input type=text id=c></input></td><td>Change in Time</td><td>(&Delta;t)</td>";
	forms[1][14] = new Array();
		forms[1][14][0] = 4;
		forms[1][14][1] = "<td><input type=text id=a></input></td><td>Power</td><td>(P)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][14][2] = "<td><input type=text id=b></input></td><td>Force</td><td>(F)</td>";
		forms[1][14][3] = "<td><input type=text id=c></input></td><td>Velocity</td><td>(v)</td>";
		forms[1][14][4] = "<td><input type=text id=d></input></td><td>Angle</td><td>(&theta;)</td>";
	forms[1][15] = new Array();
		forms[1][15][0] = 3;
		forms[1][15][1] = "<td><input type=text id=a></input></td><td>Force</td><td>(F<sub>s</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][15][2] = "<td><input type=text id=b></input></td><td>Spring Costant</td><td>(k)</td>";
		forms[1][15][3] = "<td><input type=text id=c></input></td><td>Distance</td><td>(x)</td>";
	forms[1][16] = new Array();
		forms[1][16][0] = 3;
		forms[1][16][1] = "<td><input type=text id=a></input></td><td>Potential Energy</td><td>(U<sub>s</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][16][2] = "<td><input type=text id=b></input></td><td>Spring Constant</td><td>(k)</td>";
		forms[1][16][3] = "<td><input type=text id=c></input></td><td>Distance</td><td>(x)</td>";
	forms[1][17] = new Array();
		forms[1][17][0] = 3;
		forms[1][17][1] = "<td><input type=text id=a></input></td><td>Period</td><td>(T<sub>s</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][17][2] = "<td><input type=text id=b></input></td><td>Mass</td><td>(m)</td>";
		forms[1][17][3] = "<td><input type=text id=c></input></td><td>Spring Constant</td><td>(k)</td>";
	forms[1][18] = new Array();
		forms[1][18][0] = 3;
		forms[1][18][1] = "<td><input type=text id=a></input></td><td>Period</td><td>(T<sub>p</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][18][2] = "<td><input type=text id=b></input></td><td>Length</td><td>(l)</td>";
		forms[1][18][3] = "<td><input type=text id=c></input></td><td>Acceleration due to Gravity</td><td>(g)</td>";
	forms[1][19] = new Array();
		forms[1][19][0] = 2;
		forms[1][19][1] = "<td><input type=text id=a></input></td><td>Period</td><td>(T)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][19][2] = "<td><input type=text id=b></input></td><td>Frequency</td><td>(f)</td>";
	forms[1][20] = new Array();
		forms[1][20][0] = 4;
		forms[1][20][1] = "<td><input type=text id=a></input></td><td>Force</td><td>(F)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][20][2] = "<td><input type=text id=b></input></td><td>Mass 1</td><td>(m<sub>1</sub>)</td>";
		forms[1][20][3] = "<td><input type=text id=c></input></td><td>Mass 2</td><td>(m<sub>2</sub>)</td>";
		forms[1][20][4] = "<td><input type=text id=d></input></td><td>Distance</td><td>(r)</td>";
	forms[1][21] = new Array();
		forms[1][21][0] = 4;
		forms[1][21][1] = "<td><input type=text id=a></input></td><td>Potential Energy</td><td>(U<sub>g</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[1][21][2] = "<td><input type=text id=b></input></td><td>Mass 1</td><td>(m<sub>1</sub>)</td>";
		forms[1][21][3] = "<td><input type=text id=c></input></td><td>Mass 2</td><td>(m<sub>2</sub>)</td>";
		forms[1][21][4] = "<td><input type=text id=d></input></td><td>Distance</td><td>(r)</td>";