//Waves and Optics; 10 options
forms[4] = new Array();
	forms[4][1] = new Array();
		forms[4][1][0] = 3;
		forms[4][1][1] = "<td><input type=text id=a></input></td><td>Velocity</td><td>(v)</td><td id=image style='vertical-align: top;'></td>";
		forms[4][1][2] = "<td><input type=text id=b></input></td><td>Frequency</td><td>(f)</td>";
		forms[4][1][3] = "<td><input type=text id=c></input></td><td>Wave Length</td><td>(&lambda;)</td>";
	forms[4][2] = new Array();
		forms[4][2][0] = 2;
		forms[4][2][1] = "<td><input type=text id=a></input></td><td>Index of Refraction</td><td>(n)</td><td id=image style='vertical-align: top;'></td>";
		forms[4][2][2] = "<td><input type=text id=b></input></td><td>Velocity</td><td>(v)</td>";
	forms[4][3] = new Array();
		forms[4][3][0] = 4;
		forms[4][3][1] = "<td><input type=text id=a></input></td><td>Index of Refraction 1</td><td>(n<sub>1</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[4][3][2] = "<td><input type=text id=b></input></td><td>Angle 1</td><td>(&theta;<sub>1</sub>)</td>";
		forms[4][3][3] = "<td><input type=text id=c></input></td><td>Index of Refraction 2</td><td>(n<sub>2</sub>)</td>";
		forms[4][3][4] = "<td><input type=text id=d></input></td><td>Angle 2</td><td>(&theta;<sub>2</sub>)</td>";
	forms[4][4] = new Array();
		forms[4][4][0] = 3;
		forms[4][4][1] = "<td><input type=text id=a></input></td><td>Angle</td><td>(&theta;<sub>c</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[4][4][2] = "<td><input type=text id=b></input></td><td>Index of Refraction 2</td><td>(n<sub>2</sub>)</td>";
		forms[4][4][3] = "<td><input type=text id=c></input></td><td>Index of Refraction 1</td><td>(n<sub>1</sub>)</td>";
	forms[4][5] = new Array();
		forms[4][5][0] = 3;
		forms[4][5][1] = "<td><input type=text id=a></input></td><td>Initial Distance</td><td>(x<sub>i</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[4][5][2] = "<td><input type=text id=b></input></td><td>Final Distance</td><td>(x<sub>f</sub>)</td>";
		forms[4][5][3] = "<td><input type=text id=c></input></td><td>Frequency</td><td>(f)</td>";
	forms[4][6] = new Array();
		forms[4][6][0] = 3;
		forms[4][6][1] = "<td><input type=text id=a></input></td><td>Magnification</td><td>(M)</td><td id=image style='vertical-align: top;'></td>";
		forms[4][6][2] = "<td><input type=text id=b></input></td><td>Initial Height</td><td>(h<sub>i</sub>)</td>";
		forms[4][6][3] = "<td><input type=text id=c></input></td><td>Final Height</td><td>(h<sub>f</sub>)</td>";
	forms[4][7] = new Array();
		forms[4][7][0] = 3;
		forms[4][7][1] = "<td><input type=text id=a></input></td><td>Magnification</td><td>(M)</td><td id=image style='vertical-align: top;'></td>";
		forms[4][7][2] = "<td><input type=text id=b></input></td><td>Initial Distance</td><td>(x<sub>i</sub>)</td>";
		forms[4][7][3] = "<td><input type=text id=c></input></td><td>Final Distance</td><td>(x<sub>f</sub>)</td>";
	forms[4][8] = new Array();
		forms[4][8][0] = 2;
		forms[4][8][1] = "<td><input type=text id=a></input></td><td>Frequency</td><td>(f)</td><td id=image style='vertical-align: top;'></td>";
		forms[4][8][2] = "<td><input type=text id=b></input></td><td>Radius of Curvature</td><td>(R)</td>";
	forms[4][9] = new Array();
		forms[4][9][0] = 4;
		forms[4][9][1] = "<td><input type=text id=a></input></td><td>Separation</td><td>(d)</td><td id=image style='vertical-align: top;'></td>";
		forms[4][9][2] = "<td><input type=text id=b></input></td><td>Angle</td><td>(&theta;)</td>";
		forms[4][9][3] = "<td><input type=text id=c></input></td><td>Multiplyer of Wave Length</td><td>(m)</td>";
		forms[4][9][4] = "<td><input type=text id=d></input></td><td>Wave Length</td><td>(&lambda;)</td>";
	forms[4][10] = new Array();
		forms[4][10][0] = 5;
		forms[4][10][1] = "<td><input type=text id=a></input></td><td>Position</td><td>(x)</td><td id=image style='vertical-align: top;'></td>";
		forms[4][10][2] = "<td><input type=text id=b></input></td><td>Multiplyer of Wave Length</td><td>(m)</td>";
		forms[4][10][3] = "<td><input type=text id=c></input></td><td>Wave Length</td><td>(&lambda;)</td>";
		forms[4][10][4] = "<td><input type=text id=d></input></td><td>Distance</td><td>(L)</td>";
		forms[4][10][5] = "<td><input type=text id=e></input></td><td>Separation</td><td>(d)</td>";