//Fluid Mechanics and Thermal Physics; 15 options
forms[3] = new Array();
	forms[3][1] = new Array();
		forms[3][1][0] = 5;
		forms[3][1][1] = "<td><input type=text id=a></input></td><td>Final Preasure</td><td>(P<sub>f</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[3][1][2] = "<td><input type=text id=b></input></td><td>Initial Preasure</td><td>(P<sub>i</sub>)</td>";
		forms[3][1][3] = "<td><input type=text id=c></input></td><td>Density</td><td>(p)</td>";
		forms[3][1][4] = "<td><input type=text id=d></input></td><td>Acceleration due to Gravity</td><td>(g)</td>";
		forms[3][1][5] = "<td><input type=text id=e></input></td><td>Depth</td><td>(h)</td>";
	forms[3][2] = new Array();
		forms[3][2][0] = 4;
		forms[3][2][1] = "<td><input type=text id=a></input></td><td>Force</td><td>(F<sub>buoy</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[3][2][2] = "<td><input type=text id=b></input></td><td>Density</td><td>(p)</td>";
		forms[3][2][3] = "<td><input type=text id=c></input></td><td>Volume</td><td>(V)</td>";
		forms[3][2][4] = "<td><input type=text id=d></input></td><td>Acceleration due to Gravity</td><td>(g)</td>";
	forms[3][3] = new Array();
		forms[3][3][0] = 4;
		forms[3][3][1] = "<td><input type=text id=a></input></td><td>Initial Area</td><td>(A<sub>i</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[3][3][2] = "<td><input type=text id=b></input></td><td>Initial Velocity</td><td>(v<sub>i</sub>)</td>";
		forms[3][3][3] = "<td><input type=text id=c></input></td><td>Final Area</td><td>(A<sub>f</sub>)</td>";
		forms[3][3][4] = "<td><input type=text id=d></input></td><td>Final Velocity</td><td>(v<sub>f</sub>)</td>";
	forms[3][4] = new Array();
		forms[3][4][0] = 6;
		forms[3][4][1] = "<td><input type=text id=a></input></td><td>Constant</td><td>(const.)</td><td id=image style='vertical-align: top;'></td>";
		forms[3][4][2] = "<td><input type=text id=b></input></td><td>Preasure</td><td>(P)</td>";
		forms[3][4][3] = "<td><input type=text id=c></input></td><td>Density</td><td>(p)</td>";
		forms[3][4][4] = "<td><input type=text id=d></input></td><td>Acceleration due to Gravity</td><td>(g)</td>";
		forms[3][4][5] = "<td><input type=text id=e></input></td><td>Height</td><td>(y)</td>";
		forms[3][4][6] = "<td><input type=text id=f></input></td><td>Velocity</td><td>(v)</td>";
	forms[3][5] = new Array();
		forms[3][5][0] = 4;
		forms[3][5][1] = "<td><input type=text id=a></input></td><td>Change in Length</td><td>(&Delta;l)</td><td id=image style='vertical-align: top;'></td>";
		forms[3][5][2] = "<td><input type=text id=b></input></td><td>Coefficient of Linear Expansion</td><td>(a)</td>";
		forms[3][5][3] = "<td><input type=text id=c></input></td><td>Initial Length</td><td>(l<sub>i</sub>)</td>";
		forms[3][5][4] = "<td><input type=text id=d></input></td><td>Change in Temperature</td><td>(&Delta;T)</td>";
	forms[3][6] = new Array();
		forms[3][6][0] = 5;
		forms[3][6][1] = "<td><input type=text id=a></input></td><td>Rate of Heat Transfer</td><td>(H)</td><td id=image style='vertical-align: top;'></td>";
		forms[3][6][2] = "<td><input type=text id=b></input></td><td>Thermal Conductivity</td><td>(k)</td>";
		forms[3][6][3] = "<td><input type=text id=c></input></td><td>Area</td><td>(A)</td>";
		forms[3][6][4] = "<td><input type=text id=d></input></td><td>Change in Temperature</td><td>(&Delta;T)</td>";
		forms[3][6][5] = "<td><input type=text id=e></input></td><td>Thickness</td><td>(L)</td>";
	forms[3][7] = new Array();
		forms[3][7][0] = 3;
		forms[3][7][1] = "<td><input type=text id=a></input></td><td>Preasure</td><td>(P)</td><td id=image style='vertical-align: top;'></td>";
		forms[3][7][2] = "<td><input type=text id=b></input></td><td>Force</td><td>(F)</td>";
		forms[3][7][3] = "<td><input type=text id=c></input></td><td>Area</td><td>(A)</td>";
	forms[3][8] = new Array();
		forms[3][8][0] = 4;
		forms[3][8][1] = "<td><input type=text id=a></input></td><td>Preasure</td><td>(P)</td><td id=image style='vertical-align: top;'></td>";
		forms[3][8][2] = "<td><input type=text id=b></input></td><td>Volume</td><td>(V)</td>";
		forms[3][8][3] = "<td><input type=text id=c></input></td><td>Number of Moles</td><td>(n)</td>";
		forms[3][8][4] = "<td><input type=text id=d></input></td><td>Temperature</td><td>(T)</td>";
	forms[3][9] = new Array();
		forms[3][9][0] = 5;
		forms[3][9][1] = "<td><input type=text id=a></input></td><td>Preasure</td><td>(P)</td><td id=image style='vertical-align: top;'></td>";
		forms[3][9][2] = "<td><input type=text id=b></input></td><td>Volume</td><td>(V)</td>";
		forms[3][9][3] = "<td><input type=text id=c></input></td><td>Number of Molecules</td><td>(n)</td>";
		forms[3][9][4] = "<td><input type=text id=d></input></td><td>Thermal Conductivity</td><td>(k<sub>B</sub>)</td>";
		forms[3][9][5] = "<td><input type=text id=e></input></td><td>Temperature</td><td>(T)</td>";
	forms[3][10] = new Array();
		forms[3][10][0] = 3;
		forms[3][10][1] = "<td><input type=text id=a></input></td><td>Average Molecular Kinetic Energy</td><td>(K<sub>avg</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[3][10][2] = "<td><input type=text id=b></input></td><td>Thermal Conductivity</td><td>(k<sub>B</sub>)</td>";
		forms[3][10][3] = "<td><input type=text id=c></input></td><td>Temperature</td><td>(T)</td>";
	forms[3][11] = new Array();
		forms[3][11][0] = 3;
		forms[3][11][1] = "<td><input type=text id=a></input></td><td>Root-Mean-Square Velocity</td><td>(v<sub>rms</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[3][11][2] = "<td><input type=text id=b></input></td><td>Temperature</td><td>(T)</td>";
		forms[3][11][3] = "<td><input type=text id=c></input></td><td>Molar Mass</td><td>(M)</td>";
	forms[3][12] = new Array();
		forms[3][12][0] = 3;
		forms[3][12][1] = "<td><input type=text id=a></input></td><td>Root-Mean-Square Velocity</td><td>(v<sub>rms</sub>)</td><td id=image style='vertical-align: top;'></td>";
		forms[3][12][2] = "<td><input type=text id=b></input></td><td>Temperature</td><td>(T)</td>";
		forms[3][12][3] = "<td><input type=text id=c></input></td><td>Mass of Molecule</td><td>(&mu;)</td>";
	forms[3][13] = new Array();
		forms[3][13][0] = 3;
		forms[3][13][1] = "<td><input type=text id=a></input></td><td>Work</td><td>(W)</td><td id=image style='vertical-align: top;'></td>";
		forms[3][13][2] = "<td><input type=text id=b></input></td><td>Preasure</td><td>(P)</td>";
		forms[3][13][3] = "<td><input type=text id=c></input></td><td>Change in Volume</td><td>(&Delta;V)</td>";
	forms[3][14] = new Array();
		forms[3][14][0] = 3;
		forms[3][14][1] = "<td><input type=text id=a></input></td><td>Change in Internal Energy</td><td>(&Delta;U)</td><td id=image style='vertical-align: top;'></td>";
		forms[3][14][2] = "<td><input type=text id=b></input></td><td>Heat Transfered to a System</td><td>(Q)</td>";
		forms[3][14][3] = "<td><input type=text id=c></input></td><td>Work</td><td>(W)</td>";
	forms[3][15] = new Array();
		forms[3][15][0] = 3;
		forms[3][15][1] = "<td><input type=text id=a></input></td><td>Efficiency</td><td>(e)</td><td id=image style='vertical-align: top;'></td>";
		forms[3][15][2] = "<td><input type=text id=b></input></td><td>Work</td><td>(W)</td>";
		forms[3][15][3] = "<td><input type=text id=c></input></td><td>Heat Transfered to a System</td><td>(Q<sub>H</sub>)</td>";